### ISSUE TITLE
java.lang.NoSuchMethodError: 'void org.gradle.wrapper.PathAssembler.<init>(java.io.File)'

### ISSUE THREAD

**Issue by codeconsole** [grails/grails-functional-tests#186]
```
% ./gradlew --version               

------------------------------------------------------------
Gradle 7.6.3
------------------------------------------------------------

Build time:   2023-10-04 15:59:47 UTC
Revision:     1694251d59e0d4752d547e1fd5b5020b798a7e71

Kotlin:       1.7.10
Groovy:       3.0.13
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          11.0.20 (Amazon.com Inc. 11.0.20+8-LTS)
OS:           Mac OS X 14.0 aarch64

```

```
% ./gradlew clean build --stacktrace
> Task :app1:configureChromeDriverBinary FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app1:configureChromeDriverBinary'.
> 'void org.gradle.wrapper.PathAssembler.<init>(java.io.File)'
```

```
* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app1:configureChromeDriverBinary'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:142)
        at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:282)

...

Caused by: java.lang.NoSuchMethodError: 'void org.gradle.wrapper.PathAssembler.<init>(java.io.File)'
        at org.ysb33r.grolifant.api.AbstractDistributionInstaller.getDistFromCache(AbstractDistributionInstaller.groovy:283)
        at org.ysb33r.grolifant.api.AbstractDistributionInstaller.getDistributionRoot(AbstractDistributionInstaller.groovy:98)
```

https://github.com/erdi/webdriver-binaries-gradle-plugin/issues/42

**Comment by codeconsole** [comment]
Related ?
https://gitlab.com/ysb33rOrg/grolifant/-/issues/71
